apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
    - name: liveness
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args: 
        - echo ok >/tmp/health; sleep 10; rm -rf >/tmp/health; sleep 60000
      livenessProbe:
        exec:
          command:
            - "cat"
            - /tmp/health
        initialDelaySeconds: 15
        timeoutSeconds: 1
