FROM ubuntu:22.04

WORKDIR /app

RUN apt update &&\
    apt install -y vim iproute2 iputils-ping traceroute tcpdump openssh-server dnsutils telnet lsof iotop curl  htop &&\
    rm -rf /var/lib/apt/lists/*

RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && echo 'root:dms123!!' | chpasswd && mkdir -p /run/sshd

EXPOSE 22

CMD /usr/sbin/sshd -D