apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-role
rules:
- apiGroups:
  - ""
  resources:
  - "endpoints"
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-role-binding
subjects:
- kind: ServiceAccount
  name: monitor-user
  namespace: default
roleRef:
  kind: ClusterRole
  name: monitor-role
  apiGroup: rbac.authorization.k8s.io