apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: default
spec:
  selector:
    app: ubuntu
  type: NodePort
  ports:
    - name: ubuntu-port
      port: 22
      targetPort: 22
      nodePort: 30022
      protocol: TCP
  
