apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-router
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-router
  template:
    metadata:
      labels:
        k8s-app: kube-router
    spec:
      serviceAccountName: kube-router
      containers:
      - name: kube-router
        image: cloudnativelabs/kube-router:latest
        args:
        - --enable-cni=false
        - --run-router=true
        - --bgp-graceful-restart=true
        - --run-service-proxy=false
        - --run-loadbalancer=false
        - --run-firewall=false
        - --peer-router-ips=172.21.101.16
        - --peer-router-asns=65001
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName