apiVersion: v1
kind: Pod
metadata:
  name: cmd-test-pod
spec:
  containers:
    - name: cmd-test
      image: busybox
      command: ["/bin/sh", "-c", "env | grep APP"]
      env:
        - name: APPLOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: cm-appvars
              key: apploglevel
        - name: APPDATADIR
          valueFrom:
            configMapKeyRef:
              key: appdatadir
              name: cm-appvars
  restartPolicy: Never
